### ISSUE TITLE
Publish as npm module

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-tools#1]
Could integrate other jskos tools (identifiers) and later move the latter to an independent module if needed.

**Comment by nichtich** [comment]
The schemas have been moved to [JSKOS repository](https://github.com/gbv/jskos). This may also be included in `jskos-tools` (?)

**Comment by stefandesu** [comment]
If we keep the name `jskos-validation`, I can publish it to npm.

> We may also merge this repository with the JSKOS specification repository because specification and validation are tightly connected.

I agree that they are tightly connected, but I still think that it should be separate from the JSKOS spec. It would basically double the amount of files in that repository and make it kind of cluttered. It would be fine as a separate folder, but I'd still prefer a separate repository.

**Comment by stefandesu** [comment]
It is now published as [jskos-tools](https://www.npmjs.com/package/jskos-tools).
