### ISSUE TITLE
Split validation into independent module

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-tools#12]
Validation should be split into repository and npm module jskos-validate (which might have jskos-tools as dependency).

**Comment by stefandesu** [comment]
Question: Should the `jskos-validate` repository be a fork of this repo, with everything but validation removed, so that the commit history is kept? Or should it better be a completely new repository?

**Comment by stefandesu** [comment]
Validation is now available in [jskos-validate](https://github.com/gbv/jskos-validate).
