### ISSUE TITLE
Make available via bundle

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-tools#19]
To directly use with a script tag.

**Comment by nichtich** [comment]
Would make sense for a demo HTML page where people can edit, validate, and convert JSKOS in the browser.

**Comment by stefandesu** [comment]
We should also pay attention to the bundle size. We are using a subset of the Lodash library, but [according to BundlePhobia](https://bundlephobia.com/result?p=jskos-tools@1.0.9), it adds a whopping 33 kB to our bundle size.

**Comment by nichtich** [comment]
I started with rollup, see <https://github.com/gbv/jskos-tools/tree/rollup> but stuck

**Comment by stefandesu** [comment]
I completed the Rollup configuration, but still need to test if it actually worked as intended.

**Comment by stefandesu** [comment]
I removed minification because jsDelivr has it built-in.
