### ISSUE TITLE
Improve mappingToCSV

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-tools#6]
- [x] Return object with multiple functions instead of a single function (see below).
- [x] Add support for compound mappings.
- [x] Add function to get header.
- [x] Add support for multiple mappings which also includes the column headers.

```javascript
let csv = jskos.mappingCSV({
  lineTerminator: "\r\n"
})
// single mapping
csv.fromMapping(mapping)
// multiple mappings (includes header by default)
csv.fromMappings(mappings, { header: true } )
// get header based on list of mappings (also used by "fromMappings")
csv.header(mappings)
```

This is needed for https://github.com/gbv/cocoda/issues/185.

**Comment by stefandesu** [comment]
- [ ] Include fromScheme/toScheme with an option

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stefandesu** [comment]
Bump. Related to https://github.com/gbv/cocoda/issues/185.

**Comment by stefandesu** [comment]
@nichtich How should compound mappings look like in the exported CSV?

**Comment by nichtich** [comment]
As suggested at https://github.com/gbv/cocoda/issues/185#issue-373449654: add columns such as `toNotation2`, `toNotation3`..

**Comment by stefandesu** [comment]
I missed that, thanks!

**Comment by stefandesu** [comment]
Opened a PR: https://github.com/gbv/jskos-tools/pull/20

**Comment by stefandesu** [comment]
Merged.
